name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      # Загрузка кода
      - uses: actions/checkout@v4

      # Установка Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Кеширование зависимостей
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}

      # Установка зависимостей
      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      # Запуск форматеров и линтеров
      - name: Run Black
        run: black src/ --check

      - name: Run isort
        run: isort src/ --check-only

      - name: Run flake8
        run: flake8 src/

      - name: Run pyupgrade
        run: |
          pyupgrade --py38-plus \
            $(find . -name '*.py' \
            -not -path './.git/*' \
            -not -path './solutions/*/solution.py')
